<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 57" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="/home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_DC.py" status="error" test="estimate_DC" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/home/controller/.p2/pool/plugins/org.python.pydev_5.0.0.201605051159/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_DC.py", line 55, in <module>
    list_temp = list_temp1 + list_temp2[0] + list_temp2[len(list_temp2)-1]
TypeError: can only concatenate list (not "str") to list
ERROR: Module: estimate_DC could not be imported (file: /home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_DC.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="HttpClient estimate_DC.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
